"""Seed dataset definition: categories, vocabulary, products, orders (all fictional sample data)."""
from __future__ import annotations

import random

# slug, parent, name_vi, name_en, aliases
CATEGORIES: list[tuple[str, str | None, str, str, list[str]]] = [
    ("thoi-trang-nam", None, "Thời trang nam", "Men's fashion", []),
    ("ao-nam", "thoi-trang-nam", "Áo nam", "Men's tops", []),
    ("ao-len-nam", "ao-nam", "Áo len nam", "Men's sweaters", ["sweater", "pullover", "jumper"]),
    ("ao-co-lo-nam", "ao-nam", "Áo cổ lọ nam", "Men's turtlenecks",
     ["áo len cổ lọ", "cổ lọ", "turtleneck", "polo neck"]),
    ("ao-khoac-phao-nam", "ao-nam", "Áo khoác phao nam", "Men's puffer jackets",
     ["áo phao", "áo khoác", "jacket", "coat", "áo lông vũ"]),
    ("ao-thun-nam", "ao-nam", "Áo thun nam", "Men's t-shirts", ["áo phông", "t-shirt", "tee", "polo"]),
    ("ao-so-mi-nam", "ao-nam", "Áo sơ mi nam", "Men's shirts", ["sơ mi", "shirt"]),
    ("ao-hoodie-nam", "ao-nam", "Áo hoodie nam", "Men's hoodies", ["áo nỉ", "hoodie", "sweatshirt"]),
    ("quan-nam", "thoi-trang-nam", "Quần nam", "Men's bottoms", ["pants"]),
    ("quan-jeans-nam", "quan-nam", "Quần jeans nam", "Men's jeans", ["quần jean", "quần bò", "jeans"]),
    ("quan-short-nam", "quan-nam", "Quần short nam", "Men's shorts", ["quần đùi", "shorts"]),
    ("quan-tay-nam", "quan-nam", "Quần tây nam", "Men's trousers", ["quần âu", "quần công sở", "dress pants"]),
    ("giay-nam", "thoi-trang-nam", "Giày dép nam", "Men's shoes", ["giày"]),
    ("giay-chay-bo-nam", "giay-nam", "Giày chạy bộ nam", "Men's running shoes",
     ["giày chạy", "giày thể thao", "running shoes"]),
    ("giay-sneaker-nam", "giay-nam", "Giày sneaker nam", "Men's sneakers",
     ["giày thể thao", "sneaker", "trainers"]),
    ("giay-da-nam", "giay-nam", "Giày da nam", "Men's leather shoes", ["giày tây", "oxford", "dress shoes"]),
    ("dep-sandal-nam", "giay-nam", "Dép sandal nam", "Men's sandals",
     ["dép", "sandal", "dép xỏ ngón", "flip flops"]),
    ("thoi-trang-nu", None, "Thời trang nữ", "Women's fashion", []),
    ("ao-nu", "thoi-trang-nu", "Áo nữ", "Women's tops", []),
    ("ao-len-nu", "ao-nu", "Áo len nữ", "Women's sweaters", ["sweater", "pullover", "jumper", "cardigan"]),
    ("ao-co-lo-nu", "ao-nu", "Áo cổ lọ nữ", "Women's turtlenecks",
     ["áo len cổ lọ", "cổ lọ", "turtleneck", "polo neck"]),
    ("ao-khoac-phao-nu", "ao-nu", "Áo khoác phao nữ", "Women's puffer jackets",
     ["áo phao", "áo khoác", "jacket", "coat", "áo lông vũ"]),
    ("ao-thun-nu", "ao-nu", "Áo thun nữ", "Women's t-shirts", ["áo phông", "t-shirt", "tee", "croptop"]),
    ("ao-so-mi-nu", "ao-nu", "Áo sơ mi nữ", "Women's shirts", ["sơ mi", "shirt", "blouse"]),
    ("vay-dam-nu", "thoi-trang-nu", "Váy đầm nữ", "Women's dresses and skirts", ["váy"]),
    ("dam-nu", "vay-dam-nu", "Đầm nữ", "Women's dresses", ["đầm", "váy liền", "dress"]),
    ("chan-vay-nu", "vay-dam-nu", "Chân váy nữ", "Women's skirts", ["chân váy", "skirt"]),
    ("giay-nu", "thoi-trang-nu", "Giày dép nữ", "Women's shoes", ["giày"]),
    ("giay-chay-bo-nu", "giay-nu", "Giày chạy bộ nữ", "Women's running shoes",
     ["giày chạy", "giày thể thao", "running shoes"]),
    ("giay-sneaker-nu", "giay-nu", "Giày sneaker nữ", "Women's sneakers",
     ["giày thể thao", "sneaker", "trainers"]),
    ("dep-sandal-nu", "giay-nu", "Dép sandal nữ", "Women's sandals", ["dép", "sandal", "flip flops"]),
    ("tui-xach-nu", "thoi-trang-nu", "Túi xách nữ", "Women's bags", ["túi", "bag", "handbag"]),
    ("tui-tote-nu", "tui-xach-nu", "Túi tote nữ", "Women's tote bags", ["túi tote", "túi vải", "tote bag"]),
    ("tui-deo-cheo-nu", "tui-xach-nu", "Túi đeo chéo nữ", "Women's crossbody bags",
     ["túi đeo chéo", "túi đeo vai", "crossbody"]),
    ("balo-nu", "tui-xach-nu", "Balo nữ", "Women's backpacks", ["balo", "ba lô", "backpack"]),
    ("dien-tu", None, "Điện tử", "Electronics", []),
    ("dien-thoai-may-tinh", "dien-tu", "Điện thoại và máy tính", "Phones and computers", []),
    ("dien-thoai", "dien-thoai-may-tinh", "Điện thoại", "Smartphones", ["smartphone", "phone", "điện thoại di động"]),
    ("laptop", "dien-thoai-may-tinh", "Laptop", "Laptops", ["máy tính xách tay", "notebook"]),
    ("am-thanh", "dien-tu", "Âm thanh", "Audio", []),
    ("tai-nghe", "am-thanh", "Tai nghe", "Headphones", ["headphone", "earphone", "earbuds"]),
    ("loa-bluetooth", "am-thanh", "Loa bluetooth", "Bluetooth speakers", ["loa", "speaker"]),
    ("gia-dung", None, "Gia dụng", "Home appliances", []),
    ("do-dung-nha-bep", "gia-dung", "Đồ dùng nhà bếp", "Kitchenware", []),
    ("noi-chien-khong-dau", "do-dung-nha-bep", "Nồi chiên không dầu", "Air fryers", ["nồi chiên", "air fryer"]),
    ("may-xay-sinh-to", "do-dung-nha-bep", "Máy xay sinh tố", "Blenders", ["máy xay", "blender"]),
    ("binh-giu-nhiet", "do-dung-nha-bep", "Bình giữ nhiệt", "Thermos flasks", ["bình nước", "thermos", "flask"]),
    ("thiet-bi-ve-sinh", "gia-dung", "Thiết bị vệ sinh", "Cleaning devices", []),
    ("may-hut-bui", "thiet-bi-ve-sinh", "Máy hút bụi", "Vacuum cleaners", ["robot hút bụi", "vacuum"]),
]

# attribute -> (is_hard_filterable, {value: (vi, en, synonyms, also_match)})
VOCABULARY: dict[str, tuple[bool, dict[str, tuple[str, str, list[str], list[str]]]]] = {
    "color": (True, {
        "black": ("đen", "black", ["đen", "den", "màu đen", "black", "dark"], []),
        "white": ("trắng", "white", ["trắng", "màu trắng", "white"], []),
        "gray": ("xám", "gray", ["xám", "ghi", "màu xám", "gray", "grey"], []),
        "beige": ("be", "beige", ["be", "màu be", "kem", "màu kem", "beige", "cream"], []),
        "brown": ("nâu", "brown", ["nâu", "màu nâu", "brown"], []),
        "red": ("đỏ", "red", ["đỏ", "màu đỏ", "red"], []),
        "pink": ("hồng", "pink", ["hồng", "màu hồng", "pink"], []),
        "orange": ("cam", "orange", ["cam", "màu cam", "orange"], []),
        "yellow": ("vàng", "yellow", ["vàng", "màu vàng", "yellow"], []),
        "green": ("xanh lá", "green", ["xanh lá", "xanh lá cây", "xanh", "green"], []),
        "blue": ("xanh dương", "blue", ["xanh dương", "xanh da trời", "xanh", "blue"], []),
        "navy": ("xanh navy", "navy", ["xanh navy", "xanh than", "xanh đen", "navy"], []),
        "purple": ("tím", "purple", ["tím", "màu tím", "purple"], []),
        "silver": ("bạc", "silver", ["bạc", "màu bạc", "silver"], []),
        "gold": ("vàng kim", "gold", ["vàng kim", "gold"], []),
        "multicolor": ("nhiều màu", "multicolor", ["nhiều màu", "đa sắc", "sặc sỡ", "multicolor", "colorful"], []),
    }),
    "material": (True, {
        "cotton": ("cotton", "cotton", ["cotton", "vải cotton", "coton"], []),
        "wool": ("len", "wool", ["len", "len cừu", "wool", "woolen"], []),
        "polyester": ("polyester", "polyester", ["polyester", "poly"], []),
        "linen": ("linen", "linen", ["linen", "đũi", "vải đũi", "vải linen"], []),
        "denim": ("denim", "denim", ["denim", "vải jean"], []),
        "leather": ("da thật", "leather", ["da thật", "da bò", "leather"], []),
        "synthetic_leather": ("da pu", "synthetic leather", ["da pu", "da tổng hợp", "giả da", "simili",
                                                              "synthetic leather", "faux leather", "pu leather"], []),
        "silk": ("lụa", "silk", ["lụa", "silk"], []),
        "fleece": ("nỉ", "fleece", ["nỉ", "nỉ bông", "fleece"], []),
        "down": ("lông vũ", "down", ["lông vũ", "lông vịt", "down"], []),
        "nylon": ("nylon", "nylon", ["nylon", "vải dù"], []),
        "knit": ("dệt kim", "knit", ["dệt kim", "knit", "knitted"], []),
        "canvas": ("vải bạt", "canvas", ["vải bạt", "canvas"], []),
        "rubber": ("cao su", "rubber", ["cao su", "rubber"], []),
        "metal": ("kim loại", "metal", ["kim loại", "inox", "thép không gỉ", "metal", "stainless steel"], []),
        "plastic": ("nhựa", "plastic", ["nhựa", "plastic"], []),
    }),
    "gender": (True, {
        "male": ("nam", "men", ["nam", "cho nam", "đàn ông", "men", "man", "male", "for men", "boy"], ["unisex"]),
        "female": ("nữ", "women", ["nữ", "cho nữ", "phụ nữ", "bạn gái", "con gái", "women", "woman", "female",
                                   "for women", "lady", "girl", "girlfriend"], ["unisex"]),
        "unisex": ("unisex", "unisex", ["unisex", "nam nữ"], []),
        "kids": ("trẻ em", "kids", ["trẻ em", "em bé", "kids", "children"], []),
    }),
    "season": (False, {
        "spring": ("mùa xuân", "spring", ["mùa xuân", "xuân", "spring"], []),
        "summer": ("mùa hè", "summer", ["mùa hè", "mùa hạ", "hè", "trời nóng", "nắng nóng", "summer", "hot weather"], []),
        "autumn": ("mùa thu", "autumn", ["mùa thu", "autumn", "fall"], []),
        "winter": ("mùa đông", "winter", ["mùa đông", "đông", "trời lạnh", "lạnh", "rét", "winter", "cold weather",
                                          "cold"], []),
        "all_season": ("quanh năm", "all season", ["quanh năm", "bốn mùa", "all season"], []),
    }),
    "occasion": (False, {
        "casual": ("thường ngày", "casual", ["thường ngày", "hàng ngày", "đi chơi", "dạo phố", "casual", "everyday",
                                             "daily"], []),
        "office": ("công sở", "office", ["công sở", "đi làm", "văn phòng", "phỏng vấn", "office", "work",
                                         "interview"], []),
        "sport": ("thể thao", "sport", ["tập gym", "tập luyện", "gym", "chạy bộ", "sport", "workout", "running"], []),
        "party": ("dự tiệc", "party", ["dự tiệc", "đi tiệc", "tiệc", "party"], []),
        "beach": ("đi biển", "beach", ["đi biển", "bãi biển", "biển", "đi bơi", "beach", "seaside"], []),
        "travel": ("du lịch", "travel", ["du lịch", "đi du lịch", "đi phượt", "travel", "trip"], []),
        "home": ("ở nhà", "home", ["ở nhà", "mặc nhà", "gia đình", "home"], []),
        "formal": ("trang trọng", "formal", ["trang trọng", "lịch sự", "sự kiện", "phỏng vấn", "formal"], []),
    }),
    "style": (False, {
        "basic": ("cơ bản", "basic", ["cơ bản", "đơn giản", "trơn", "basic"], []),
        "streetwear": ("đường phố", "streetwear", ["đường phố", "streetwear", "street style"], []),
        "vintage": ("cổ điển", "vintage", ["cổ điển", "retro", "vintage"], []),
        "elegant": ("thanh lịch", "elegant", ["thanh lịch", "sang trọng", "lịch lãm", "elegant"], []),
        "sporty": ("năng động", "sporty", ["năng động", "sporty", "athletic"], []),
        "minimal": ("tối giản", "minimal", ["tối giản", "minimal", "minimalist"], []),
    }),
    "warmth": (False, {
        "low": ("mát", "light", ["mát", "thoáng mát", "mát mẻ", "thoáng khí", "breathable", "cool", "lightweight"], []),
        "medium": ("vừa phải", "moderate", ["vừa ấm", "ấm vừa", "moderate warmth"], []),
        "high": ("giữ ấm", "warm", ["giữ ấm", "giữ nhiệt", "ấm áp", "ấm", "warm", "thermal", "keep warm"], []),
    }),
}

COLOR_RGB = {
    "black": (28, 28, 32), "white": (250, 250, 250), "gray": (140, 140, 145), "beige": (222, 200, 160),
    "brown": (110, 70, 40), "red": (200, 30, 40), "pink": (240, 150, 180), "orange": (240, 130, 30),
    "yellow": (245, 210, 40), "green": (50, 150, 70), "blue": (50, 110, 210), "navy": (25, 40, 100),
    "purple": (120, 60, 160), "silver": (192, 196, 204), "gold": (212, 175, 55), "multicolor": (1, 2, 3),
}

# cat, name, brand, price, colors, materials, gender, season, occasion, style, warmth, shape, description
Spec = tuple
PRODUCTS: list[Spec] = [
    ("ao-len-nam", "Áo len cổ tròn nam dệt kim", "Uniqlo", 399000, ["navy"], ["wool", "knit"], "male",
     ["autumn", "winter"], ["casual", "office"], ["basic"], "high", "sweater",
     "Áo len dệt kim cổ tròn, bề mặt mềm, form vừa vặn."),
    ("ao-len-nam", "Áo len nam họa tiết vintage", "Routine", 459000, ["brown"], ["wool"], "male",
     ["autumn", "winter"], ["casual"], ["vintage"], "high", "sweater",
     "Áo len họa tiết kẻ ngang phong cách retro."),
    ("ao-len-nam", "Men's Merino Wool Crewneck Sweater", "Uniqlo", 599000, ["gray"], ["wool"], "male",
     ["autumn", "winter"], ["office", "casual"], ["minimal"], "high", "sweater",
     "Lightweight merino sweater with a clean crew neck."),
    ("ao-co-lo-nam", "Áo len cổ lọ nam giữ nhiệt", "Uniqlo", 349000, ["black"], ["knit", "wool"], "male",
     ["winter"], ["casual", "office"], ["minimal"], "high", "turtleneck",
     "Áo cổ lọ ôm nhẹ, mặc lót hoặc mặc ngoài đều đẹp."),
    ("ao-co-lo-nam", "Áo cổ lọ nam basic", "Coolmate", 249000, ["beige"], ["cotton", "knit"], "male",
     ["autumn", "winter"], ["casual"], ["basic"], "medium", "turtleneck",
     "Áo cổ lọ cotton co giãn, màu be dễ phối đồ."),
    ("ao-khoac-phao-nam", "Áo khoác phao nam siêu nhẹ", "Uniqlo", 899000, ["black"], ["down", "nylon"], "male",
     ["winter"], ["casual", "travel"], ["basic"], "high", "puffer",
     "Áo phao lông vũ siêu nhẹ, gấp gọn bỏ túi."),
    ("ao-khoac-phao-nam", "Áo phao nam trần bông dáng ngắn", "The North Face", 2890000, ["navy"],
     ["polyester", "down"], "male", ["winter"], ["travel", "casual"], ["streetwear"], "high", "puffer",
     "Áo phao chống nước nhẹ, mũ liền, dùng cho thời tiết rất lạnh."),
    ("ao-thun-nam", "Áo thun cotton nam basic cổ tròn", "Coolmate", 149000, ["white"], ["cotton"], "male",
     ["summer", "all_season"], ["casual"], ["basic"], "low", "tshirt",
     "Áo thun cotton 100% thấm hút mồ hôi."),
    ("ao-thun-nam", "Áo thun nam oversize in chữ", "Routine", 199000, ["black"], ["cotton"], "male",
     ["summer"], ["casual"], ["streetwear"], "low", "tshirt", "Áo thun form rộng in chữ ngực."),
    ("ao-thun-nam", "Áo polo nam cá sấu", "Polo Club", 329000, ["blue"], ["cotton"], "male",
     ["summer"], ["office", "casual"], ["elegant"], "low", "tshirt", "Áo polo vải cá sấu thoáng khí."),
    ("ao-so-mi-nam", "Áo sơ mi nam trắng dài tay công sở", "Việt Tiến", 420000, ["white"], ["cotton"], "male",
     ["all_season"], ["office", "formal"], ["elegant"], "low", "shirt",
     "Sơ mi trắng dài tay, cổ đứng, ít nhăn."),
    ("ao-so-mi-nam", "Áo sơ mi linen nam", "Coolmate", 299000, ["beige"], ["linen"], "male",
     ["summer"], ["beach", "travel", "casual"], ["minimal"], "low", "shirt",
     "Sơ mi vải đũi mỏng nhẹ, mặc mát."),
    ("ao-hoodie-nam", "Áo hoodie nỉ nam màu be", "Routine", 399000, ["beige"], ["fleece", "cotton"], "male",
     ["autumn", "winter"], ["casual"], ["streetwear"], "medium", "hoodie",
     "Hoodie nỉ bông có mũ, túi kangaroo."),
    ("ao-hoodie-nam", "Hoodie nỉ bông unisex", "Routine", 429000, ["gray"], ["fleece"], "unisex",
     ["winter"], ["casual"], ["streetwear"], "high", "hoodie", "Hoodie nỉ dày dặn, lót bông mềm."),
    ("quan-jeans-nam", "Quần jeans nam slim fit xanh", "Levi's", 790000, ["blue"], ["denim"], "male",
     ["all_season"], ["casual"], ["basic"], "medium", "pants", "Quần jeans ống côn, co giãn nhẹ."),
    ("quan-jeans-nam", "Quần jean nam đen rách gối", "Routine", 520000, ["black"], ["denim"], "male",
     ["all_season"], ["casual"], ["streetwear"], "medium", "pants", "Quần jean đen wash, rách gối."),
    ("quan-short-nam", "Quần short kaki nam", "Coolmate", 249000, ["beige"], ["cotton"], "male",
     ["summer"], ["beach", "casual", "travel"], ["basic"], "low", "shorts", "Quần short kaki ngang gối."),
    ("quan-short-nam", "Quần short thể thao nam", "Nike", 390000, ["black"], ["polyester"], "male",
     ["summer"], ["sport"], ["sporty"], "low", "shorts", "Quần short dệt thoáng khí, có túi khóa kéo."),
    ("quan-tay-nam", "Quần tây nam công sở", "Việt Tiến", 450000, ["gray"], ["polyester"], "male",
     ["all_season"], ["office", "formal"], ["elegant"], "medium", "pants", "Quần tây ống đứng, ít nhăn."),
    ("giay-chay-bo-nam", "Giày chạy bộ Nike Air Zoom Pegasus 40", "Nike", 3200000, ["black", "white"], ["nylon", "rubber"],
     "male", ["all_season"], ["sport"], ["sporty"], "low", "running_shoe", "Giày chạy bộ êm, đế Air Zoom phản hồi nhanh."),
    ("giay-chay-bo-nam", "Nike Revolution 6 Running Shoes", "Nike", 1590000, ["black"], ["nylon", "rubber"], "male",
     ["all_season"], ["sport"], ["sporty"], "low", "running_shoe", "Entry-level running shoes with a soft foam midsole."),
    ("giay-chay-bo-nam", "Giày chạy bộ Asics Gel-Contend", "Asics", 1890000, ["blue"], ["nylon", "rubber"], "male",
     ["all_season"], ["sport"], ["sporty"], "low", "running_shoe", "Giày chạy bộ đệm gel giảm chấn."),
    ("giay-sneaker-nam", "Giày sneaker trắng Converse Chuck 70", "Converse", 1700000, ["white"], ["canvas", "rubber"],
     "male", ["all_season"], ["casual"], ["vintage"], "low", "sneaker", "Sneaker cổ thấp vải canvas, phong cách cổ điển."),
    ("giay-sneaker-nam", "Sneaker da nam Adidas Stan Smith", "Adidas", 2300000, ["white"], ["leather", "rubber"],
     "male", ["all_season"], ["casual"], ["minimal"], "low", "sneaker", "Sneaker da trắng tối giản."),
    ("giay-da-nam", "Giày da nam công sở Oxford", "Vento", 1200000, ["brown"], ["leather"], "male",
     ["all_season"], ["office", "formal"], ["elegant"], "low", "dress_shoe", "Giày Oxford da bò thật, đế khâu."),
    ("dep-sandal-nam", "Dép xỏ ngón nam đi biển", "Biti's", 190000, ["blue"], ["rubber"], "male",
     ["summer"], ["beach", "home"], ["basic"], "low", "sandal", "Dép cao su nhẹ, chống trượt, đi biển hoặc đi trong nhà."),
    ("ao-len-nu", "Áo len nữ cổ tròn màu hồng", "Routine", 359000, ["pink"], ["wool", "knit"], "female",
     ["autumn", "winter"], ["casual"], ["elegant"], "high", "sweater", "Áo len mềm màu hồng pastel."),
    ("ao-len-nu", "Cardigan len nữ dáng rộng", "Mango", 429000, ["beige"], ["wool"], "female",
     ["autumn", "winter"], ["casual", "office"], ["minimal"], "high", "sweater", "Cardigan khoác ngoài cài cúc."),
    ("ao-co-lo-nu", "Áo cổ lọ nữ dệt kim", "Uniqlo", 329000, ["black"], ["knit"], "female",
     ["winter"], ["casual", "office"], ["minimal"], "high", "turtleneck", "Áo cổ lọ ôm dáng, co giãn tốt."),
    ("ao-co-lo-nu", "Áo len cổ lọ nữ màu đỏ", "Mango", 379000, ["red"], ["wool"], "female",
     ["winter"], ["party", "casual"], ["elegant"], "high", "turtleneck", "Áo len cổ lọ đỏ, hợp dịp lễ."),
    ("ao-khoac-phao-nu", "Áo phao nữ dáng ngắn", "Uniqlo", 1100000, ["white"], ["down", "nylon"], "female",
     ["winter"], ["casual", "travel"], ["basic"], "high", "puffer", "Áo phao ngắn trần bông nhẹ."),
    ("ao-khoac-phao-nu", "Áo khoác phao nữ dáng dài", "Zara", 1400000, ["black"], ["polyester", "down"], "female",
     ["winter"], ["casual", "travel"], ["elegant"], "high", "puffer", "Áo phao dáng dài có mũ lông."),
    ("ao-thun-nu", "Áo thun nữ croptop", "Zara", 179000, ["white"], ["cotton"], "female",
     ["summer"], ["casual"], ["streetwear"], "low", "tshirt", "Áo croptop cotton co giãn."),
    ("ao-thun-nu", "Áo thun nữ babytee hồng", "Coolmate", 159000, ["pink"], ["cotton"], "female",
     ["summer"], ["casual"], ["basic"], "low", "tshirt", "Áo babytee ôm nhẹ."),
    ("ao-so-mi-nu", "Áo sơ mi nữ lụa", "Mango", 520000, ["beige"], ["silk"], "female",
     ["spring", "autumn"], ["office", "formal"], ["elegant"], "low", "shirt", "Sơ mi lụa mềm rủ, tay dài."),
    ("dam-nu", "Đầm maxi hoa đi biển", "Zara", 590000, ["multicolor"], ["polyester"], "female",
     ["summer"], ["beach", "travel"], ["elegant"], "low", "dress", "Đầm maxi họa tiết hoa nhiều màu, chất voan nhẹ."),
    ("dam-nu", "Đầm công sở nữ dáng chữ A", "Mango", 650000, ["black"], ["polyester"], "female",
     ["all_season"], ["office", "formal", "party"], ["elegant"], "medium", "dress", "Đầm đen tay lỡ dáng chữ A."),
    ("chan-vay-nu", "Chân váy chữ A nữ", "Zara", 329000, ["gray"], ["wool"], "female",
     ["autumn", "winter"], ["office", "casual"], ["minimal"], "medium", "skirt", "Chân váy xếp ly dài qua gối."),
    ("giay-chay-bo-nu", "Giày chạy bộ nữ Asics Gel-Excite", "Asics", 1790000, ["pink"], ["nylon", "rubber"],
     "female", ["all_season"], ["sport"], ["sporty"], "low", "running_shoe", "Giày chạy bộ nhẹ cho nữ."),
    ("giay-sneaker-nu", "Sneaker nữ trắng đế platform", "Vans", 890000, ["white"], ["canvas", "rubber"], "female",
     ["all_season"], ["casual"], ["streetwear"], "low", "sneaker", "Sneaker đế dày tăng chiều cao."),
    ("dep-sandal-nu", "Sandal nữ quai ngang đi biển", "Biti's", 250000, ["beige"], ["synthetic_leather", "rubber"],
     "female", ["summer"], ["beach", "casual"], ["basic"], "low", "sandal", "Sandal quai ngang đế êm."),
    ("tui-tote-nu", "Túi tote vải canvas", "Routine", 220000, ["beige"], ["canvas"], "female",
     ["summer"], ["casual", "beach"], ["minimal"], "low", "tote", "Túi tote vải bạt dày, đựng vừa laptop mỏng."),
    ("tui-tote-nu", "Túi tote da nữ", "Charles & Keith", 1250000, ["black"], ["synthetic_leather"], "female",
     ["all_season"], ["office"], ["elegant"], "low", "tote", "Túi tote da PU form đứng."),
    ("tui-deo-cheo-nu", "Túi đeo chéo nữ mini", "Charles & Keith", 890000, ["red"], ["synthetic_leather"], "female",
     ["all_season"], ["party", "casual"], ["elegant"], "low", "crossbody", "Túi mini đeo chéo nắp gập."),
    ("tui-deo-cheo-nu", "Túi đeo chéo da nữ", "Pedro", 1490000, ["brown"], ["leather"], "female",
     ["all_season"], ["casual", "office"], ["vintage"], "low", "crossbody", "Túi da bò thật, dây đeo điều chỉnh."),
    ("balo-nu", "Balo laptop nữ chống nước", "Samsonite", 780000, ["gray"], ["polyester"], "female",
     ["all_season"], ["office", "travel"], ["minimal"], "low", "backpack", "Balo ngăn laptop 15 inch, vải chống nước."),
    ("dien-thoai", "Điện thoại Samsung Galaxy S24", "Samsung", 18900000, ["black"], ["metal"], "unisex",
     [], ["casual"], [], "", "phone", "Smartphone màn hình AMOLED 6.2 inch."),
    ("dien-thoai", "iPhone 15 Pro 128GB", "Apple", 28900000, ["gray"], ["metal"], "unisex",
     [], ["casual"], [], "", "phone", "Smartphone khung titan, chip A17 Pro."),
    ("laptop", "Laptop Dell Inspiron 14", "Dell", 15900000, ["silver"], ["metal"], "unisex",
     [], ["office"], [], "", "laptop", "Laptop văn phòng 14 inch, RAM 16GB."),
    ("laptop", "MacBook Air M2 13 inch", "Apple", 24900000, ["silver"], ["metal"], "unisex",
     [], ["office", "travel"], [], "", "laptop", "Ultrabook mỏng nhẹ, pin 18 giờ."),
    ("tai-nghe", "Tai nghe Bluetooth chống ồn Sony WH-1000XM5", "Sony", 6500000, ["black"], ["plastic"], "unisex",
     [], ["travel", "office"], [], "", "headphones", "Noise cancelling headphones with 30 hours of battery."),
    ("tai-nghe", "Tai nghe AirPods Pro 2", "Apple", 5900000, ["white"], ["plastic"], "unisex",
     [], ["casual", "sport"], [], "", "headphones", "Tai nghe true wireless chống ồn chủ động."),
    ("loa-bluetooth", "Loa Bluetooth JBL Flip 6", "JBL", 2700000, ["blue"], ["nylon", "rubber"], "unisex",
     [], ["travel", "beach"], [], "", "speaker", "Loa chống nước IP67, pin 12 giờ, mang đi biển."),
    ("noi-chien-khong-dau", "Nồi chiên không dầu Philips 4.1L", "Philips", 2500000, ["black"], ["plastic"], "unisex",
     [], ["home"], [], "", "airfryer", "Nồi chiên không dầu dung tích 4.1 lít."),
    ("noi-chien-khong-dau", "Air Fryer 6L màn hình cảm ứng", "Lock&Lock", 1900000, ["white"], ["plastic"], "unisex",
     [], ["home"], [], "", "airfryer", "Nồi chiên 6 lít, 8 chế độ nấu."),
    ("may-xay-sinh-to", "Máy xay sinh tố mini cầm tay", "Sunhouse", 690000, ["green"], ["plastic"], "unisex",
     [], ["home"], [], "", "blender", "Máy xay cối thủy tinh 600ml, lưỡi dao 4 cánh."),
    ("binh-giu-nhiet", "Bình giữ nhiệt Lock&Lock 500ml", "Lock&Lock", 350000, ["blue"], ["metal"], "unisex",
     [], ["travel", "office"], [], "", "bottle", "Bình inox giữ nóng 12 giờ, giữ lạnh 24 giờ."),
    ("binh-giu-nhiet", "Bình nước inox 750ml", "Elmich", 290000, ["silver"], ["metal"], "unisex",
     [], ["travel", "sport"], [], "", "bottle", "Bình inox 304 nắp vặn kín."),
    ("may-hut-bui", "Robot hút bụi lau nhà Xiaomi", "Xiaomi", 5500000, ["white"], ["plastic"], "unisex",
     [], ["home"], [], "", "vacuum", "Robot hút bụi lau nhà, định vị laser."),
]

ORDERS = [
    # order_code, customer, status, created_at, [(product index (1-based), qty)]
    ("20260915", "C001", "DELIVERED", "2026-09-15T10:12:00+07:00", [(8, 2), (15, 1)]),
    ("20260928", "C001", "DELIVERED", "2026-09-28T19:40:00+07:00", [(19, 1)]),
    ("20261001", "C001", "SHIPPING", "2026-10-01T09:30:00+07:00", [(1, 2)]),
    ("20261005", "C001", "CONFIRMED", "2026-10-05T21:05:00+07:00", [(6, 1), (4, 1)]),
    ("20260920", "C002", "CANCELLED", "2026-09-20T08:00:00+07:00", [(46, 1)]),
    ("20261002", "C002", "PENDING", "2026-10-02T14:25:00+07:00", [(31, 1), (36, 1)]),
]


def build_products() -> list[dict]:
    rng = random.Random(2026)
    out = []
    for i, s in enumerate(PRODUCTS, start=1):
        cat, name, brand, price, colors, mats, gender, seasons, occ, style, warmth, shape, desc = s
        tags: dict[str, list[str]] = {}
        for key, vals in (("season", seasons), ("occasion", occ), ("style", style),
                          ("warmth", [warmth] if warmth else [])):
            if vals:
                tags[key] = list(vals)
        pid = f"P{i:06d}"
        out.append({
            "id": pid, "source": "seed", "source_id": str(i), "source_url": None,
            "name": name, "description": desc, "brand": brand, "category": cat,
            "price": price, "original_price": int(round(price * rng.choice([1.0, 1.15, 1.25]) / 1000) * 1000) or price,
            "stock": 0 if i == 24 else rng.randint(5, 120),
            "rating": round(rng.uniform(4.0, 4.9), 1), "rating_count": rng.randint(20, 900),
            "sold_count": rng.randint(30, 4000),
            "attributes": {"color": colors, "material": mats, "gender": [gender]},
            "tags": tags, "images": [f"images/{pid}_0.jpg"],
            "_shape": shape,
        })
    return out
